Async fft. Broken: need to implement Send on everything
Compilation output:

    -*- mode: compilation; default-directory: "~/Projects/rust_pulse/" -*-
    Compilation started at Sun Apr 12 12:02:34

    cargo build
       Compiling rust_pulse v0.0.1 (file:///home/ali/Projects/rust_pulse)
    /home/ali/Projects/rust_pulse/src/main.rs:257:12: 263:7 error: the trait `core::marker::Send` is not implemented for the type `*mut ncurses_wrapper::ext::WINDOW`
    /home/ali/Projects/rust_pulse/src/main.rs:257     stream.set_read_callback(move |mut stream, nbytes| {
    /home/ali/Projects/rust_pulse/src/main.rs:258         let foo: &[u8] = stream.peek().unwrap();
    /home/ali/Projects/rust_pulse/src/main.rs:259         fft.feed_u8_data(stream.peek().unwrap());
    /home/ali/Projects/rust_pulse/src/main.rs:260         fft.execute();
    /home/ali/Projects/rust_pulse/src/main.rs:261         fft.compute_output();
    /home/ali/Projects/rust_pulse/src/main.rs:262         vis.render_frame(fft.get_output()).unwrap();
                                                  ...
    /home/ali/Projects/rust_pulse/src/main.rs:257:12: 263:7 error: the trait `core::marker::Send` is not implemented for the type `*mut fftw_wrapper::ext::fftw_plan`
    /home/ali/Projects/rust_pulse/src/main.rs:257     stream.set_read_callback(move |mut stream, nbytes| {
    /home/ali/Projects/rust_pulse/src/main.rs:258         let foo: &[u8] = stream.peek().unwrap();
    /home/ali/Projects/rust_pulse/src/main.rs:259         fft.feed_u8_data(stream.peek().unwrap());
    /home/ali/Projects/rust_pulse/src/main.rs:260         fft.execute();
    /home/ali/Projects/rust_pulse/src/main.rs:261         fft.compute_output();
    /home/ali/Projects/rust_pulse/src/main.rs:262         vis.render_frame(fft.get_output()).unwrap();
                                                  ...
    /home/ali/Projects/rust_pulse/src/main.rs:257:12: 263:7 error: the trait `core::marker::Send` is not implemented for the type `*const f64`
    /home/ali/Projects/rust_pulse/src/main.rs:257     stream.set_read_callback(move |mut stream, nbytes| {
    /home/ali/Projects/rust_pulse/src/main.rs:258         let foo: &[u8] = stream.peek().unwrap();
    /home/ali/Projects/rust_pulse/src/main.rs:259         fft.feed_u8_data(stream.peek().unwrap());
    /home/ali/Projects/rust_pulse/src/main.rs:260         fft.execute();
    /home/ali/Projects/rust_pulse/src/main.rs:261         fft.compute_output();
    /home/ali/Projects/rust_pulse/src/main.rs:262         vis.render_frame(fft.get_output()).unwrap();
                                                  ...
    /home/ali/Projects/rust_pulse/src/main.rs:257:12: 263:7 error: the trait `core::marker::Send` is not implemented for the type `*mut f64`
    /home/ali/Projects/rust_pulse/src/main.rs:257     stream.set_read_callback(move |mut stream, nbytes| {
    /home/ali/Projects/rust_pulse/src/main.rs:258         let foo: &[u8] = stream.peek().unwrap();
    /home/ali/Projects/rust_pulse/src/main.rs:259         fft.feed_u8_data(stream.peek().unwrap());
    /home/ali/Projects/rust_pulse/src/main.rs:260         fft.execute();
    /home/ali/Projects/rust_pulse/src/main.rs:261         fft.compute_output();
    /home/ali/Projects/rust_pulse/src/main.rs:262         vis.render_frame(fft.get_output()).unwrap();
                                                  ...
    /home/ali/Projects/rust_pulse/src/main.rs:257:12: 263:7 error: the trait `core::marker::Send` is not implemented for the type `*const fftw_wrapper::FftwComplex`
    /home/ali/Projects/rust_pulse/src/main.rs:257     stream.set_read_callback(move |mut stream, nbytes| {
    /home/ali/Projects/rust_pulse/src/main.rs:258         let foo: &[u8] = stream.peek().unwrap();
    /home/ali/Projects/rust_pulse/src/main.rs:259         fft.feed_u8_data(stream.peek().unwrap());
    /home/ali/Projects/rust_pulse/src/main.rs:260         fft.execute();
    /home/ali/Projects/rust_pulse/src/main.rs:261         fft.compute_output();
    /home/ali/Projects/rust_pulse/src/main.rs:262         vis.render_frame(fft.get_output()).unwrap();
                                                  ...
    /home/ali/Projects/rust_pulse/src/main.rs:257:12: 263:7 error: the trait `core::marker::Send` is not implemented for the type `*mut fftw_wrapper::FftwComplex`
    /home/ali/Projects/rust_pulse/src/main.rs:257     stream.set_read_callback(move |mut stream, nbytes| {
    /home/ali/Projects/rust_pulse/src/main.rs:258         let foo: &[u8] = stream.peek().unwrap();
    /home/ali/Projects/rust_pulse/src/main.rs:259         fft.feed_u8_data(stream.peek().unwrap());
    /home/ali/Projects/rust_pulse/src/main.rs:260         fft.execute();
    /home/ali/Projects/rust_pulse/src/main.rs:261         fft.compute_output();
    /home/ali/Projects/rust_pulse/src/main.rs:262         vis.render_frame(fft.get_output()).unwrap();
                                                  ...
    error: aborting due to 6 previous errors
    Could not compile `rust_pulse`.

    To learn more, run the command again with --verbose.

    Compilation exited abnormally with code 101 at Sun Apr 12 12:02:34